export const sectionsHtmlResult = `
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4g2ndquh">
<h1>Heading1</h1>
<div class="heading-section-content">
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4g5ark4z">
<h2>Heading2</h2>
<div class="heading-section-content">
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4g7y5dfi">
<h3>Heading3</h3>
<div class="heading-section-content">
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4galj6q0">
<h4>Heading4</h4>
<div class="heading-section-content">
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4gd8x00j">
<h5>Heading5</h5>
<div class="heading-section-content">
<section class="heading-section" data-diplodoc-key="heading-section" data-diplodoc-id="heading-section-4gfwatb1">
<h6>Heading6</h6>
<div class="heading-section-content"></div>
</section>
</div>
</section>
</div>
</section>
</div>
</section>
</div>
</section>
</div>
</section>
`.trimStart();

export const commonHeadingTokens = [
    {
        type: 'heading_open',
        tag: 'h1',
        attrs: null,
        map: [0, 1],
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '#',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'inline',
        tag: '',
        attrs: null,
        map: [0, 1],
        nesting: 0,
        level: 1,
        children: [
            {
                type: 'text',
                tag: '',
                attrs: null,
                map: null,
                nesting: 0,
                level: 0,
                children: null,
                content: 'Heading1',
                markup: '',
                info: '',
                meta: null,
                block: false,
                hidden: false,
            },
        ],
        content: 'Heading1',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_close',
        tag: 'h1',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '#',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_open',
        tag: 'h2',
        attrs: null,
        map: [2, 3],
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '##',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'inline',
        tag: '',
        attrs: null,
        map: [2, 3],
        nesting: 0,
        level: 1,
        children: [
            {
                type: 'text',
                tag: '',
                attrs: null,
                map: null,
                nesting: 0,
                level: 0,
                children: null,
                content: 'Heading2',
                markup: '',
                info: '',
                meta: null,
                block: false,
                hidden: false,
            },
        ],
        content: 'Heading2',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_close',
        tag: 'h2',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '##',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
];

export const foldingHeadingTokens = [
    {
        type: 'heading_section_open',
        tag: 'section',
        attrs: [
            ['class', 'heading-section'],
            ['data-diplodoc-key', 'heading-section'],
            ['data-diplodoc-id', 'heading-section-4g2ndquh'],
        ],
        map: null,
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_open',
        tag: 'h1',
        attrs: null,
        map: [0, 1],
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '#+',
        info: '',
        meta: {folding: true},
        block: true,
        hidden: false,
    },
    {
        type: 'inline',
        tag: '',
        attrs: null,
        map: [0, 1],
        nesting: 0,
        level: 1,
        children: [
            {
                type: 'text',
                tag: '',
                attrs: null,
                map: null,
                nesting: 0,
                level: 0,
                children: null,
                content: 'Feading1',
                markup: '',
                info: '',
                meta: null,
                block: false,
                hidden: false,
            },
        ],
        content: 'Feading1',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_close',
        tag: 'h1',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '#+',
        info: '',
        meta: {folding: true},
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_content_open',
        tag: 'div',
        attrs: [['class', 'heading-section-content']],
        map: null,
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_open',
        tag: 'section',
        attrs: [
            ['class', 'heading-section'],
            ['data-diplodoc-key', 'heading-section'],
            ['data-diplodoc-id', 'heading-section-4g5ark4z'],
        ],
        map: null,
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_open',
        tag: 'h2',
        attrs: null,
        map: [2, 3],
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '##+',
        info: '',
        meta: {folding: true},
        block: true,
        hidden: false,
    },
    {
        type: 'inline',
        tag: '',
        attrs: null,
        map: [2, 3],
        nesting: 0,
        level: 1,
        children: [
            {
                type: 'text',
                tag: '',
                attrs: null,
                map: null,
                nesting: 0,
                level: 0,
                children: null,
                content: 'Feading2',
                markup: '',
                info: '',
                meta: null,
                block: false,
                hidden: false,
            },
        ],
        content: 'Feading2',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_close',
        tag: 'h2',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '##+',
        info: '',
        meta: {folding: true},
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_content_open',
        tag: 'div',
        attrs: [['class', 'heading-section-content']],
        map: null,
        nesting: 1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_content_close',
        tag: 'div',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_close',
        tag: 'section',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_content_close',
        tag: 'div',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
    {
        type: 'heading_section_close',
        tag: 'section',
        attrs: null,
        map: null,
        nesting: -1,
        level: 0,
        children: null,
        content: '',
        markup: '',
        info: '',
        meta: null,
        block: true,
        hidden: false,
    },
];
